### ISSUE TITLE
Possible bug in NVDSP.mm when copying the results back to audio buffer

### ISSUE THREAD

**Issue by crontab** [bartolsthoorn/NVDSP#26] opened 2015-08-02 19:20 UTC
In method filterContiguousData (line 81) when you copy the results back:

    memcpy(data, tOutputBuffer, numFrames * sizeof(float));

I think it should be

    memcpy(data, tOutputBuffer + 2, numFrames * sizeof(float));

I haven't tested this yet, but if it is a bug it may go unnoticed in audio.

Many other examples on the Net do this. See e.g. http://vboehm.net/2015/04/using-vdsp_deq22-correctly/

**Comment by bartolsthoorn** [comment] 2015-08-02 20:57
It has been a long time since I last touched this code, but I think what you are looking for is this: https://github.com/bartolsthoorn/NVDSP/blob/b074bbd32a0897a18c29d0a444ca2a12a0e365be/NVDSP.mm#L75
So in fact, the buffer is copied starting from the 3rd index, just like your line does, using `&(tInputBuffer[2])`. The code in NVDSP is presented in a different way than the page you mentioned, but operates in a similar way. Each time, 2 samples are stored to ensure a smooth transition between buffers. An error in this process will immediately lead to noticeable distortion. The buffers are very short, and without handling trailing/leading samples correctly, a fast "clicking" distortion will be introduced at each new buffer that calls `filterContiguousData`.
I will close this for now, but please correct me if I am wrong and definitely let me know if you do hear any distortion caused by the problem you mentioned.

**Comment by crontab** [comment] 2015-08-02 22:53
Strangely, there is no difference in audio either way, with or without +2! But I believe the way vDSP_deq22() works is, the output data start at +2. A lot of examples on the Internet confirm that.

**Comment by bartolsthoorn** [comment] 2015-08-03 06:26
Hmm, even the official API states "This function creates N new values in output vector C, beginning with its third element." - https://developer.apple.com/library/prerelease/ios/documentation/Accelerate/Reference/vDSPRef/index.html#//apple_ref/c/func/vDSP_deq22

I looked into it and I think the only difference is that NVDSP outputs the first two samples (in `gInputKeepBuffer`) the very first time, but after that it does not matter (in practice) whether you output +2, because the buffer start/end still connect perfectly. If this is true, NVDSP introduces a 2-sample delay though, which is what I will look for now. I will do some testing and maybe add the +2 to make NVDSP match the default way of using vDSP_deq22.

**Comment by bartolsthoorn** [comment] 2015-08-03 07:07
@crontab Tested it, and you were right, using the `+2` is slightly better, it prevents the 2 samples delay and leads to the same audio. Could you make a merge request with the new line?
```objective-c
memcpy(data, tOutputBuffer + 2, numFrames * sizeof(float));
```

**Closed** 2015-08-03 17:30 UTC
