### ISSUE TITLE
Thread safety and efficiency

### ISSUE THREAD

**Issue by crontab** [bartolsthoorn/NVDSP#27] opened 2015-08-03 13:24 UTC
First of all, thanks for putting this code up on the Internet, I'm pretty sure it helped a lot of people in making their first steps into iOS/OSX audio, like it did for me. However, I decided to switch to The Amazing Audio Engine and my own implementation of filters (like NVDSP did with Novocaine) and I thought I'd share why.

First reason is thread safety: neither Novocaine nor NVDSP are thread safe as far as I can tell. Because audio processing happens in a separate high-priority thread, while e.g. filter parameters can be changed from the main thread, you need to design your classes with thread safety in mind. For example, when a user changes one of the peaking filter parameters and while you are calculating your 5 coefficients, the audio thread may use them for filtering the audio. These race conditions may not be so rare as you might think, especially with smaller buffer sizes on OS X, but they won't always result in audible glitches. In this particular case, if you want to avoid locking, you need to have two copies of the coefficients and also have an atomic flag that indicates (using OSAtomicX()) whether they were copied to the real-time thread or not. As one example of what could be done.

But then comes the problem of efficiency and again, neither Novocaine nor NVDSP were designed with efficiency in mind. For example, you do dynamic allocation of buffers in each cycle and it's just a horrendously bad thing to do. Let alone that Objective-C messaging is scattered everywhere in real-time code. On top of that, if you want to implement a multi-band EQ you could avoid copying vDSP_deq22() buffers for each of the filters by swapping them. I've noticed a dozen of other things that could've been optimized.

TAAE by contrast is made with these things in mind. The code that uses TAAE may be a little uglier, but at least all real-time code is pure C, no dynamic allocation and no I/O happening there, and the documentation stresses that user code that's executed in the real-time thread should adhere to the same principles. TAAE can even give you warnings in Debug mode that your real-time routine is taking too long to execute.

Anyway, like I said I'm still grateful to those who wrote and contributed to Novocaine and NVDSP but once you consider efficiency and thread safety (you don't want to drain your users' phone battery and you don't want them to hear occasional glitches, right?) you realize that these two libraries fall short. Fixing these things though might require a serious effort, if not a complete revamp. In any case unfortunately I won't be contributing to these repositories but I'm willing to help to anyone who'd consider redoing them.

Thanks again, and have a nice coding!

**Comment by bartolsthoorn** [comment] 2015-08-03 17:24
Thank you for your message and the time you put into writing it, but I disagree with some of your points, considering the following:

1. NVDSP is completely stand-alone and does not rely on Novocaine. It simply processes raw audio samples, and can be used with any audio set-up. Any argument about Novocaine itself is irrelevant. So why is NVDSP called "Novocaine" DSP? At the time NVDSP was created, there simply wasn't another library providing the same functionality Novocaine does.

2. When NVDSP was released in 2012, TAAE was still at a very early development stage, and for quite some time there was no other library out there providing anything like TAAE. Also, NVDSP is a *very* minimal library. It deliberately is not as feature rich as TAAE and it should, in my opinion, not be compared to TAAE.

3. The audio thread calculates the coefficients right before processing a buffer, so a race condition like you described is impossible. You can change the _parameters_ of the filters outside the audio thread, but the new coefficients will only be calculated once a new buffer is processed.

4. The glitches you might hear are either the real-time routine taking too long, or samples distorting (too much gain). NVDSP is very small and minimal and can be used in any way you want, which means you can mess up, but it is very easy in use because of its minimalism, and it allows the programmer to build extra safety checks where necessary.

But thank you for taking the time to voice your thoughts. I am sure the NVDSP code can be optimised though, and I am interested to hear about battery saving techniques or other code improvements.

**Comment by crontab** [comment] 2015-08-03 17:35
On point 3, here is what you have:

- (void) setCenterFrequency:(float)_centerFrequency {
    centerFrequency = _centerFrequency;
    [self calculateCoefficients];
}

- (void) calculateCoefficients {
    if ((centerFrequency != 0.0f) && (Q != 0.0f)) {
        
        [self intermediateVariables:centerFrequency Q:Q];
        
        float A = sqrt(pow(10.0f, (G/20.0f)));
        
        a0 = (1  + (alpha / A));
        b0 = (1 + (alpha * A))     / a0; 
        b1 = (-2 * omegaC)         / a0; 
        b2 = (1 - (alpha * A))     / a0;
        a1 = (-2 * omegaC)         / a0; 
        a2 = (1 - alpha / A)       / a0;
        
        [super setCoefficients];
    }
}

On the one hand, setting the frequency from the audio thread at each cycle is hyper-overkill. Otherwise setting it from the main thread (e.g. as a result of a user moving a slider) introduces a race condition, because you are setting 5 or more parameters.

Either way, like I said NVDSP was not designed with efficiency in mind, and the above is not the only problem with it. How about dynamic allocation of buffers within the audio thread, etc.

Quite honestly, fixing these things would require a complete rewrite of the code.

I'd suggest that you leave this issue open so that the users are aware. It would be unfair with respect to your users to sweep these things under the carpet by closing the issues I open. But of course it's up to you at the end of the day ;)

**Comment by bartolsthoorn** [comment] 2015-08-03 17:56
Ah now I understand your point about the race condition, sorry I missed it the first time. I must say that I never noticed any glitches when moving a slider, but I can imagine it can cause problems. By the way, I closed the other issue because it is fixed, I added the buffer offset and figured out why it was needed but not noticeable in audio.

I will re-open this issue so someone else may take a look at it in the future.

**Comment by crontab** [comment] 2015-08-03 18:08
Bart, I think a few things can be fixed straight away.

Firstly, things that can be done outside the loop should be done outside the loop. For your filters you can recommend your users to set the parameters (frequency, gain etc.) from within the main thread but not the audio callback routine (And you could fix it in your example app in the first place). This way the coefficients will be calculated only when something is changed.

Next would be to pass the coefficients to the audio thread. What I did in my library was: have two versions of the coefficient arrays: `userCoeffs` and `realTimeCoeffs`. You also declare an `int coeffsCopied`. The idea is that when the user sets parameters and userCoeffs get recalculated, you drop the `coeffsCopied` flag.

Then in NVDSP's audio thread you do something like this:

```
if (OSAtomicCompareAndSwap32(0, 1, &self->coeffsCopied))
	self->realTimeCoeffs = self->userCoeffs;
```

and go on feeding self->realTimeCoeffs to vDSP.

Thus, copying of the coefficients happens only once after the get modified by the user. This way you avoid race conditions and avoid locking.

Another obvious thing to do is to kill dynamic allocations in filterContiguousData. These buffers can be allocated/re-allocated only when numFrames don't fit the buffer. You can start with 0 in fact, so that next time you see numFrames is not zero you do your first allocation. In reality this will happen only once for each filter during app's execution, as CoreAudio usually sends the same amount of data (e.g. 512 on OSX and I think it's 4096 on iOS).

**Comment by bartolsthoorn** [comment] 2015-08-04 10:33
Thank you for the clear instructions on what to change. I do not have time to implement this, unfortunately, but maybe someone else will come along and perform the changes you proposed.

**Comment by rweichler** [comment] 2015-11-03 14:25
I think I may have a suggestion for implementing what @crontab is suggesting here:

> if you want to implement a multi-band EQ you could avoid copying vDSP_deq22() buffers for each of the filters by swapping them.

Basically, the problem lies in this code:

```objc

- (void) filterContiguousData: (float *)data numFrames:(UInt32)numFrames channel:(UInt32)channel {
    
    // Provide buffer for processing
    float tInputBuffer[numFrames + 2];
    float tOutputBuffer[numFrames + 2];
    
    // Copy the data
    memcpy(tInputBuffer, gInputKeepBuffer[channel], 2 * sizeof(float));
    memcpy(tOutputBuffer, gOutputKeepBuffer[channel], 2 * sizeof(float));
    memcpy(&(tInputBuffer[2]), data, numFrames * sizeof(float)); //HUGE OVERHEAD
    
    // Do the processing
    vDSP_deq22(tInputBuffer, 1, coefficients, tOutputBuffer, 1, numFrames);
    
    // Copy the data
    memcpy(data, tOutputBuffer + 2, numFrames * sizeof(float)); //HUGE OVERHEAD
    memcpy(gInputKeepBuffer[channel], &(tInputBuffer[numFrames]), 2 * sizeof(float));
    memcpy(gOutputKeepBuffer[channel], &(tOutputBuffer[numFrames]), 2 * sizeof(float));
}
```
So with those two `memcpy`'s I commented, you only really need to do them once. One time before you do the filtering, and one time after you do the filtering. You can just set `tInputBuffer` to be equal to `tOutputBuffer` and just pass it into the next time you filter it. The problem is there really isn't a good way of doing this without either making the API way harder to use, or making it way less thread safe. It would basically go from this:

```objc
// apply the filter
for (int i = 0; i < 10; i++) {
	[PEQ[i] filterData:outData numFrames:numFrames numChannels:numChannels];
}

```

to something like this:

```objc
NVDSPBuffer *buffer = [NVDSPBuffer bufferWithData:outData numFrames:numFrames numChannels:numChannels];
// apply the filter
for (int i = 0; i < 10; i++) {
    [PEQ[i] filterBuffer:buffer];
}
[buffer copyBuffer:outData];
[
```

You basically have the temporary buffers stored in this `NVDSPBuffer` object which only copies to and from the actual sample data when its only absolutely necessary.

The only downside to this is that the API is slightly more to take in...

**Comment by bartolsthoorn** [comment] 2015-11-04 18:39
Thanks a lot for your suggestion. I think I personally would like to encourage people to actually adjust NVDSP to their liking and to keep NVDSP in its current, very minimal, elegant state. I would also happily merge a performance-optimised version (with possibly a different API) in a separate branch.

**Comment by bartolsthoorn** [comment] 2015-11-04 18:41
Alternatively, I would also recommend a performance-optimised fork in the README for that matter.

**Comment by spiderweb62** [comment] 2017-05-20 23:28
I am trying to convert your code into Swift, and I wasn't sure about these 2 lines. Reading on the Japanese translated link, it looks like we need the last 2 samples (unfiltered and filtered) in the KeepBuffer, should:
`    memcpy(gInputKeepBuffer[channel], &(tInputBuffer[numFrames]), 2 * sizeof(float));
    memcpy(gOutputKeepBuffer[channel], &(tOutputBuffer[numFrames]), 2 * sizeof(float));
`

Be more like:
`
    memcpy(gInputKeepBuffer[channel], &(tInputBuffer[numFrames - 2]), 2 * sizeof(float));
    memcpy(gOutputKeepBuffer[channel], &(tOutputBuffer[numFrames - 2]), 2 * sizeof(float));
`

I have done some testing on Playground and I confirmed the latter.

**Comment by bartolsthoorn** [comment] 2017-05-21 11:57
@spiderweb62 
I'm not sure so of that, but I wrote this 2 years ago so who knows haha! The 2 samples are needed in order to keep the input and output signals continuous. 

The Japanese source does not use the `-2` and note that the `tInputBuffer` is actually allocated with `+2`: https://github.com/bartolsthoorn/NVDSP/blob/master/NVDSP.mm#L69-L70
Also, see the vDSP_deq22 docs: https://developer.apple.com/reference/accelerate/1450297-vdsp_deq22?language=objc, which shows N + 2 elements are need in order to calculate N new elements (which I assume are then calculated all the way to the end of the N+2 buffer, because:
```
 memcpy(data, tOutputBuffer + 2, numFrames * sizeof(float));
```
skips the first two samples.

By the way, this seems to be unrelated to this issue so I'm unsure why you brought it up here.

**Comment by spiderweb62** [comment] 2017-05-23 19:13
Oops, you're right, sorry! I guess this would go into the general comments section (if there would be one) :-)

**Closed** 2017-09-22 09:07 UTC
